import * as dotenv from "dotenv";
import { baseSepolia, polygon, polygonAmoy } from "viem/chains";
dotenv.config();
import { z } from "zod";
// BOBA Network is an EVM-compatible L2 on Ethereum

const envVarsSchema = z.object({
  PORT: z.string().default("80").transform((str) => parseInt(str, 10)),  
  JWT_SECRET: z.string(),
  EXPIREATION_MINUTE:z.string(),
  DB_URL: z.string(),
  CHAINID : z.string(),
  // PROVIDER_URL: z.string(),
  PAYMASTERAPI_KEY:z.string(),
  CHAINID80002:z.string(),
  CONTRACR_ADDRESS: z.string(),
  CHAINID137:z.string(),
  CHAINID84532:z.string(),
  TELEGRAM_TOKEN:z.string(),
  BUNDLER_URL:z.string(),
  PAYMASTERAPI_KEY_URL:z.string(),
  ADMINID:z.string(),
  DUNE_API_KEY:z.string(),
  CONTRACT_ADDRESS_XDC:z.string(),
  ETHERSPOTAPIKEY:z.string(),
  PROVIDER_URL_AVAX:z.string(),
  PROVIDER_URL_AVAX2:z.string(),
  PROVIDER_URL_AVAX3:z.string(),
  PROVIDER_URL_AVAX4:z.string(),
  PROVIDER_URL_AVAX1:z.string(),
  PROVIDER_URL_AVAX5:z.string(),
  PROVIDER_URL_AVAX6:z.string(),
  PROVIDER_URL_AVAX7:z.string(),
  PROVIDER_URL_AVAX8:z.string(),
  PROVIDER_URL_AVAX9:z.string(),
  PROVIDER_URL_AVAX10:z.string(),
  PROVIDER_URL_AVAX11:z.string(),
  PROVIDER_URL_AVAX12:z.string(),
  PROVIDER_URL_AVAX13:z.string(),
  PROVIDER_URL_AVAX14:z.string(),
  PROVIDER_URL_AVAX15:z.string(),
  ADMIN_PRIVATEKEY_AVAX:z.string(),
  ADMIN_PRIVATEKEY_AVAX1:z.string(),
  ADMIN_PRIVATEKEY_AVAX2:z.string(),
  ADMIN_PRIVATEKEY_AVAX3:z.string(),
  ADMIN_PRIVATEKEY_AVAX4:z.string(),
  ADMIN_PRIVATEKEY_AVAX5:z.string(),
  ADMIN_PRIVATEKEY_AVAX6:z.string(),
  ADMIN_PRIVATEKEY_AVAX7:z.string(),
  ADMIN_PRIVATEKEY_AVAX8:z.string(),
  ADMIN_PRIVATEKEY_AVAX9:z.string(),
  ADMIN_PRIVATEKEY_AVAX10:z.string(),
  ADMIN_PRIVATEKEY_AVAX11:z.string(),
  ADMIN_PRIVATEKEY_AVAX12:z.string(),
  ADMIN_PRIVATEKEY_AVAX13:z.string(),
  ADMIN_PRIVATEKEY_AVAX14:z.string(),
  ADMIN_PRIVATEKEY_AVAX15:z.string(),
  ADMIN_PRIVATEKEY_AVAX16:z.string(),
  CONTRACT_ADDRESS_AVAX:z.string(),
  // BOBA Network Configuration
  CHAINID_BOBA:z.string(),
  PROVIDER_URL_BOBA:z.string(),
  PROVIDER_URL_BOBA_2:z.string(),
  PROVIDER_URL_BOBA_3:z.string(),
  PROVIDER_URL_BOBA_4:z.string(),
  PROVIDER_URL_BOBA_5:z.string(),
  PROVIDER_URL_BOBA_6:z.string(),
  PROVIDER_URL_BOBA_7:z.string(),
  PROVIDER_URL_BOBA_8:z.string(),
  PROVIDER_URL_BOBA_9:z.string(),
  PROVIDER_URL_BOBA_10:z.string(),
  PROVIDER_URL_BOBA_11:z.string(),
  PROVIDER_URL_BOBA_12:z.string(),
  PROVIDER_URL_BOBA_13:z.string(),
  PROVIDER_URL_BOBA_14:z.string(),
  PROVIDER_URL_BOBA_15:z.string(),
  ADMIN_PRIVATEKEY_BOBA:z.string(),
  ADMIN_PRIVATEKEY_BOBA1:z.string(),
  ADMIN_PRIVATEKEY_BOBA2:z.string(),
  ADMIN_PRIVATEKEY_BOBA3:z.string(),
  ADMIN_PRIVATEKEY_BOBA4:z.string(),
  ADMIN_PRIVATEKEY_BOBA5:z.string(),
  ADMIN_PRIVATEKEY_BOBA6:z.string(),
  ADMIN_PRIVATEKEY_BOBA7:z.string(),
  ADMIN_PRIVATEKEY_BOBA8:z.string(),
  ADMIN_PRIVATEKEY_BOBA9:z.string(),
  ADMIN_PRIVATEKEY_BOBA10:z.string(),
  ADMIN_PRIVATEKEY_BOBA11:z.string(),
  ADMIN_PRIVATEKEY_BOBA12:z.string(),
  ADMIN_PRIVATEKEY_BOBA13:z.string(),
  ADMIN_PRIVATEKEY_BOBA14:z.string(),
  ADMIN_PRIVATEKEY_BOBA15:z.string(),
  ADMIN_PRIVATEKEY_BOBA16:z.string(),
});

const envVars = envVarsSchema.parse(process.env);
export const envConfigs = {
  port: envVars.PORT || 8080,
  jwtsecret:envVars.JWT_SECRET,
  accessExpirationMinutes:envVars.EXPIREATION_MINUTE,
  db_url:envVars.DB_URL,
  chainId : envVars.CHAINID,
  // providerUrl: envVars.PROVIDER_URL,
  paymaster_apikey : envVars.PAYMASTERAPI_KEY,
  contractAddress : envVars.CONTRACR_ADDRESS,
  chain80002:envVars.CHAINID80002,
  chain137:envVars.CHAINID137,
  chain84532 :envVars.CHAINID84532,
  telegram_token:envVars.TELEGRAM_TOKEN,
  bundlerUrl:envVars.BUNDLER_URL,
  paymaster_apikey_url : envVars.PAYMASTERAPI_KEY_URL,
  adminId:envVars.ADMINID,
  duneApikey:envVars.DUNE_API_KEY,
  provider_url_AVAX :envVars.PROVIDER_URL_AVAX,
  adminPrivatKey_avax:envVars.ADMIN_PRIVATEKEY_AVAX,
  adminPrivatKey_avax1:envVars.ADMIN_PRIVATEKEY_AVAX1,
  adminPrivatKey_avax2:envVars.ADMIN_PRIVATEKEY_AVAX2,
  adminPrivatKey_avax3:envVars.ADMIN_PRIVATEKEY_AVAX3,
  adminPrivatKey_avax4:envVars.ADMIN_PRIVATEKEY_AVAX4,
  adminPrivatKey_avax5:envVars.ADMIN_PRIVATEKEY_AVAX5,
  adminPrivatKey_avax6:envVars.ADMIN_PRIVATEKEY_AVAX6,
  adminPrivatKey_avax7:envVars.ADMIN_PRIVATEKEY_AVAX7,
  adminPrivatKey_avax8:envVars.ADMIN_PRIVATEKEY_AVAX8,
  adminPrivatKey_avax9:envVars.ADMIN_PRIVATEKEY_AVAX9,
  adminPrivatKey_avax10:envVars.ADMIN_PRIVATEKEY_AVAX10,
  adminPrivatKey_avax11:envVars.ADMIN_PRIVATEKEY_AVAX11,
  adminPrivatKey_avax12:envVars.ADMIN_PRIVATEKEY_AVAX12,
  adminPrivatKey_avax13:envVars.ADMIN_PRIVATEKEY_AVAX13,
  adminPrivatKey_avax14:envVars.ADMIN_PRIVATEKEY_AVAX14,
  adminPrivatKey_avax15:envVars.ADMIN_PRIVATEKEY_AVAX15,
  adminPrivatKey_avax16:envVars.ADMIN_PRIVATEKEY_AVAX16,
  provider_url_AVAX1 :envVars.PROVIDER_URL_AVAX1,
  provider_url_AVAX2:envVars.PROVIDER_URL_AVAX2,
  provider_url_AVAX3 :envVars.PROVIDER_URL_AVAX3,
  provider_url_AVAX4 :envVars.PROVIDER_URL_AVAX4,
  provider_url_AVAX5 :envVars.PROVIDER_URL_AVAX5,
  provider_url_AVAX6 :envVars.PROVIDER_URL_AVAX6,
  provider_url_AVAX7 :envVars.PROVIDER_URL_AVAX7,
  provider_url_AVAX8 :envVars.PROVIDER_URL_AVAX8,
  provider_url_AVAX9 :envVars.PROVIDER_URL_AVAX9,
  provider_url_AVAX10 :envVars.PROVIDER_URL_AVAX10,
  provider_url_AVAX11 :envVars.PROVIDER_URL_AVAX11,
  provider_url_AVAX12:envVars.PROVIDER_URL_AVAX12,
  provider_url_AVAX13:envVars.PROVIDER_URL_AVAX13,
  provider_url_AVAX14:envVars.PROVIDER_URL_AVAX14,
  provider_url_AVAX15:envVars.PROVIDER_URL_AVAX15,
  contract_address_avax :envVars.CONTRACT_ADDRESS_AVAX,
  etherspot_api_Key:envVars.ETHERSPOTAPIKEY,
  
  // BOBA Network Configuration
  chainId_boba: envVars.CHAINID_BOBA,
  provider_url_BOBA: envVars.PROVIDER_URL_BOBA,
  provider_url_BOBA1: envVars.PROVIDER_URL_BOBA_2,
  provider_url_BOBA2: envVars.PROVIDER_URL_BOBA_3,
  provider_url_BOBA3: envVars.PROVIDER_URL_BOBA_4,
  provider_url_BOBA4: envVars.PROVIDER_URL_BOBA_5,
  provider_url_BOBA5: envVars.PROVIDER_URL_BOBA_6,
  provider_url_BOBA6: envVars.PROVIDER_URL_BOBA_7,
  provider_url_BOBA7: envVars.PROVIDER_URL_BOBA_8,
  provider_url_BOBA8: envVars.PROVIDER_URL_BOBA_9,
  provider_url_BOBA9: envVars.PROVIDER_URL_BOBA_10,
  provider_url_BOBA10: envVars.PROVIDER_URL_BOBA_11,
  provider_url_BOBA11: envVars.PROVIDER_URL_BOBA_12,
  provider_url_BOBA12: envVars.PROVIDER_URL_BOBA_13,
  provider_url_BOBA13: envVars.PROVIDER_URL_BOBA_14,
  provider_url_BOBA14: envVars.PROVIDER_URL_BOBA_15,
  adminPrivatKey_boba: envVars.ADMIN_PRIVATEKEY_BOBA,
  adminPrivatKey_boba1: envVars.ADMIN_PRIVATEKEY_BOBA1,
  adminPrivatKey_boba2: envVars.ADMIN_PRIVATEKEY_BOBA2,
  adminPrivatKey_boba3: envVars.ADMIN_PRIVATEKEY_BOBA3,
  adminPrivatKey_boba4: envVars.ADMIN_PRIVATEKEY_BOBA4,
  adminPrivatKey_boba5: envVars.ADMIN_PRIVATEKEY_BOBA5,
  adminPrivatKey_boba6: envVars.ADMIN_PRIVATEKEY_BOBA6,
  adminPrivatKey_boba7: envVars.ADMIN_PRIVATEKEY_BOBA7,
  adminPrivatKey_boba8: envVars.ADMIN_PRIVATEKEY_BOBA8,
  adminPrivatKey_boba9: envVars.ADMIN_PRIVATEKEY_BOBA9,
  adminPrivatKey_boba10: envVars.ADMIN_PRIVATEKEY_BOBA10,
  adminPrivatKey_boba11: envVars.ADMIN_PRIVATEKEY_BOBA11,
  adminPrivatKey_boba12: envVars.ADMIN_PRIVATEKEY_BOBA12,
  adminPrivatKey_boba13: envVars.ADMIN_PRIVATEKEY_BOBA13,
  adminPrivatKey_boba14: envVars.ADMIN_PRIVATEKEY_BOBA14,
  adminPrivatKey_boba15: envVars.ADMIN_PRIVATEKEY_BOBA15,
  adminPrivatKey_boba16: envVars.ADMIN_PRIVATEKEY_BOBA16,

};

export const chainIdToChainName: any = {
  137: polygon,
  80002:polygonAmoy,
};


export const chainIdToBundlerUrl:any ={
  137:envConfigs.chain137,
  80002:envConfigs.chain80002,
}






